#!/usr/bin/env python3

import os, sys
import time, subprocess

os.chdir("../")
sys.path.insert(0, os.getcwd())
from clicore.runGPIO import runGPIO
os.chdir("cli")


def __set(chnls: [], val: int):
   try:
      os.system("clear")
      run_gpio: runGPIO = runGPIO()
      run_gpio.init()
      for ch in chnls:
         ch: str = ch
         if not ch.isdigit():
            continue
         run_gpio.set(int(ch), val)
         time.sleep(0.332)
   except Exception as e:
      print(e)

def __ping():
   try:
      os.system("clear")
      run_gpio: runGPIO = runGPIO()
      run_gpio.init()
      run_gpio.ping()
   except Exception as e:
      print(e)

def __help():
   os.system("clear")
   with open("info/help") as f:
      buff = f.read()
   print(buff)

def __env():
   os.system("clear")
   cmd = "env"
   proc = subprocess.Popen([cmd], stdout=subprocess.PIPE, shell=True)
   (out, err) = proc.communicate()
   lns = out.decode("utf-8").split("\n")
   print("\n\t[ env ]\n")
   _ = [print(f"\t\t{xl}") for xl in lns if xl.startswith("GPIO_")]

def main():
   if len(sys.argv) == 1:
      __help()
   if len(sys.argv) == 2 and sys.argv[1] == "-h":
      __help()
   if len(sys.argv) == 2 and sys.argv[1] == "-env":
      __env()
   if len(sys.argv) == 2 and sys.argv[1] == "-ping":
      __ping()
   if len(sys.argv) == 4 and sys.argv[1] == "-set":
      arg0, arg1 = sys.argv[2:]
      chls: [] = arg0.replace("chnls:=", "").split(",")
      val: int = int(arg1.replace("val:=", ""))
      __set(chls, val)
   # -- -- the end -- --
   print("\n\n")


# -- -- -- -- -- -- -- -- -- -- -- --
if __name__ == "__main__":
   main()
